### ISSUE TITLE
Computer Vision API throws 400 Bad Request errors

### ISSUE THREAD

**Issue by jst-cyr** [markstiles/SitecoreCognitiveServices#36]
Hey there, I've been trying to fix a few bugs with the Face and Computer Vision API and got them to connect to the APIs to resolve authentication/endpoint URL issues.

However, the Computer Vision API is returning 'bad request' errors now that authentication is working. The way that the octet stream is put together seems to be somehow failing on the current Computer Vision API.

I tested a similar request via the online testing tool, except using a URL, and the request worked fine. So I know the endpoint/key issues for authentication are resolved. I was reading this:

https://www.packtpub.com/mapt/book/application_development/9781786467843/2/ch02lvl1sec13/learning-what-an-image-is-about-using-computer-vision-api

Seems to indicate an issue with the request body. There is a new VisionServiceClient class available, may be worth looking into using that and making the VisionRepository work more like the FaceRepository does.

**Comment by markstiles** [comment]
Yeah, I've recently had to stop using their clients because they seem to fall out of sync with the api's. I can take a look at it. I usually use the api test pages to figure out what they're expecting since those seem to work pretty consistently.
