### ISSUE TITLE
Issue Regarding the Content Item Analysis

### ISSUE THREAD

**Issue by doodleM** [markstiles/SitecoreCognitiveServices#37]
Hi Mark,

I am facing the issue regarding the analysis for the content item. On clicking the content item, i am not able to see the "Reanalyze" & "Reanalyze All Descendants" & "View Analysis" button in cognitive tab. Please suggest what am i missing for the "Link Analysis" , "KeyPhrase Analysis" etc because i am not able to see these tabs currently.

Thanks,
Rakesh Bhatt

**Comment by markstiles** [comment]
Are you trying to use it on regular content or images? In the latest version, the analysis is only for images in the media library.

**Comment by doodleM** [comment]
The image analysis is working fine. I was trying this on the regular content, there i was not able to see that analysis options. I was following through your blog so i thought it would be included in the same.

Also, i am getting 401 unauthorized on bot framework. I debugged the code and it is appending appid in the url. Should i have to register the app somewhere on Azure portal or what i am doing wrong. Please suggest.

Thanks for your revert.

**Comment by markstiles** [comment]
The original post was for the image search but if you want to setup the chat bot you should refer to this article: https://www.markstiles.net/blog/2017/8/3/sitecore-cognitive-services-ole/

To answer you're question, yes, you should have an azure application setup that's connected to a Luis.ai account. The article has fairly good instructions.

**Comment by doodleM** [comment]
Thank you so much Mark. It worked like a charm :)

I am really keen to have a look on the content analysis part also. It would be great if you could share that also.

**Comment by markstiles** [comment]
Glad you got it working. I just removed the feature because I wasn't using it for anything more than just displaying values. There's also a lot of open ended questions before I have a good idea of what should be analyzed. For example, how to select which fields to analyze and what analysis to run on each field. Not everything makes sense to be analyzed in the same way. 

All the APIs are still there so you can always wire them up to do what you need and use the launch demo to practice with.

**Comment by doodleM** [comment]
Sure mark, i will try to make some new modifications at my end practicing on the solution.

Thanks for helping out here. Your blog & this solution is really great way to learn about this technology & integration with sitecore is really amazing job and i keeps on exploring it.

Thanks,
Rakesh Bhatt
